spring:
  application:
  name: demo
  datasource:
    url: jdbc:h2:mem:mydemodb
#    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
      settings.trace: false
      settings.web-allow-others: false