name: CI/CD Pipeline for Groovy Demo Project

on:
  push:
    branches:
      - main  # Esegui il processo quando vengono effettuati push sul branch principale
  pull_request:
    branches:
      - main  # Esegui il processo quando vengono aperte pull request sul branch principale

jobs:
  build:
    runs-on: ubuntu-latest  # Utilizza l'ultima versione di Ubuntu come ambiente di esecuzione

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Esegui il checkout della repository

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Imposta la versione di Java

      - name: Build with Maven
        run: mvn clean install  # Esegui il comando per la build del progetto con Maven

      - name: Run Tests
        run: mvn test  # Esegui i test del progetto con Maven
